### ISSUE TITLE
Possible cross-mod integration with Thaumic Energistics?

### ISSUE THREAD

**Issue by ReneM** [DjGiannuzz/Thaumcraft-NEI-Plugin#13]
Would it be possible to add support between the Thaumcraft NEI plugin's new shift+click functionality and the [Thaumic Energistics](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2150151-1-7-10-tc4-ae2-thaumic-energistics) Arcane Crafting Terminal (an Arcane Worktable in AE2).

I'm not sure which mod (if not both) would require changes, so I've made a duplicate issue on the Thaumic Energistics issue tracker.

Nividica/ThaumicEnergistics#135

**Comment by Nividica** [comment]
@DjGiannuzz would you prefer to open an API that I can register with, or would you prefer that I include a couple function in my API that you can call?
I've not worked much with NEI, however I think all you would need from me is the class of my GUI and somewhere to pass the recipe items.

**Comment by DjGiannuzz** [comment]
@Nividica Since Applied Energistics e and Thaumic Energistics are both open source I shouldn't have any problem registering an handler for your mod only if it is installed, so I should have what I need without any API. 
Next version of TNP should have the integration for your mod, I'll let you know if I need anything.

**Comment by Nividica** [comment]
Currently the function I use on server side to set the grid from NEI is ContainerPartArcaneCraftingTerminal.onClientNEIRequestSetCraftingGrid. It is designed to accept an array of type "IAEItemStack", so if you call it directly you will need to call on the AE api to transform itemstacks into their AE counterparts.
That particular function takes care of ensuring the crafting grid can be cleared and searching the AE network for matches to place in the grid. However if you want/need me to write an overload that just takes itemstacks then send me a shout and I'll get it included.

**Comment by MaienM** [comment]
Any progress on this? I love the idea of this mod, but currently it's sadly of quite limited use when paired with Thaumic Energistics.

**Comment by Nividica** [comment]
Added a couple new API calls that should make this considerably, I hope, easier for you.
The first lets you get the class of the ACT Gui, the second lets you set the ACT Crafting grid.

https://github.com/Nividica/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/api/IInteractionHelper.java

Let me know if it gives you any trouble.

**Comment by Nividica** [comment]
This can now be closed.
@DjGiannuzzI had an epiphany about how to do this, I could just register my overlay handler with your recipe handlers via standard NEI calls. The solution has been staring me in the face, I just didn't realize it.
