### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by EnderSam** [DjGiannuzz/Thaumcraft-NEI-Plugin#15]
http://pastebin.com/AgXGVbpa

for some reason clicking U on thaumium provides that weird crash.

**Comment by ubermentat** [comment]
Similar crash on my end, only mine's an Array Out-Of-Bounds error: http://pastebin.com/kTb0ZGDv
Pressing U on any item causes this crash, whether it's a Thaumcraft item or not. Crash happens with any combination of the last three versions of CodeChickenCore/NEI and this mod, but only when Thaumic Energistics is also installed.

**Comment by EmanueleGiannuzzi** [comment]
You are using the latest version of CCC/NEI.
To avoid many other problems I should keep the recommended version of CodeChickenCore and NotEnoughItems in my Dev Environment, so please download the recommended versions from here: http://chickenbones.net/Pages/links.html
