### ISSUE TITLE
Crashes When Looking at Infusion Recipe

### ISSUE THREAD

**Issue by xilleto** [DjGiannuzz/Thaumcraft-NEI-Plugin#17]
Crashes when looking at the Infusion Recipe for Advanced Golems. Seems to be related to the golems from Thaumic Horizons which have no texture.

http://pastebin.com/eE4e7ZbQ

**Comment by EmanueleGiannuzzi** [comment]
I'm sorry, but I can't fix this on my side.
You should report this to TheKentington, the author of Thaumic Horizons.
