### ISSUE TITLE
Crash when shift-click nei recipe

### ISSUE THREAD

**Issue by nogamenofun98** [DjGiannuzz/Thaumcraft-NEI-Plugin#19]
http://pastebin.com/X4x6KErV

crash when sift-click the essential storage recipe in the thaumcraft's crafting table...(crash in storage housing only and the finished storage item like 1K storage)

**Comment by nogamenofun98** [comment]
Some information from thaumic energistic author:

https://github.com/Nividica/ThaumicEnergistics/issues/210#issuecomment-118460905

**Comment by EmanueleGiannuzzi** [comment]
You are using the Latest Version of Not Enough Items.
Please downgrade to the Recommended one.
http://chickenbones.net/Pages/links.html

**Comment by nogamenofun98** [comment]
so is nei problem not thaumic plugin problem?

**Comment by EmanueleGiannuzzi** [comment]
Those version are just incompatible. 
When NEI 1.0.5.X will became the recommended version I will update my mod.

**Comment by midorlo** [comment]
As I use WAILA, which needs the newest NEI, im currently in a struggle. Any chance you prerelease what you got to fix this issue?
